CREATE TABLE vehicles (
VehicleID INT PRIMARY KEY IDENTITY(1,1),
Model VARCHAR(255) UNIQUE NOT NULL,
Registration VARCHAR(255) NOT NULL,
YOM INT,
Color VARCHAR(255) NOT NULL,
Capacity INT,
FuelType VARCHAR(255) NOT NULL,
Transmission VARCHAR(255) NOT NULL,
DailyHirePrice DECIMAL(18,2),
Condition VARCHAR(255) NOT NULL,
DateAdded DATETIME 
);



CREATE TABLE clients (
ClientID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(255),
Gender VARCHAR(255) NOT NULL,
Email VARCHAR(255),
Phone VARCHAR(255),
Address VARCHAR(255) NOT NULL
);



CREATE TABLE orders (
Id INT PRIMARY KEY IDENTITY(1,1),
VehicleID INT NOT NULL,
ClientID INT NOT NULL,
ConditionBefore VARCHAR(255) NOT NULL,
ConditionAfter VARCHAR(255) NOT NULL,
RentDate DATETIME,
Status VARCHAR(255),
ReturnDate DATETIME,
DailyHirePrice DECIMAL(18,2),
DateAdded DATETIME,
FOREIGN KEY (VehicleID) REFERENCES vehicles (VehicleID),
FOREIGN KEY (ClientID) REFERENCES clients (ClientID)
);



CREATE TABLE company (
CompanyID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(255),
Email VARCHAR(255),
Phone VARCHAR(255),
Address VARCHAR(255) NOT NULL,
DateAdded DATETIME
);